### ISSUE TITLE
bot nulis sama bot ytmp3 error

### ISSUE THREAD

**Issue by re-Destro** [fdciabdul/termux-whatsapp-bot#7]
bot nulis errornya soalnya output pas kekirim cuma gambar buku saja, tidak ada teksnya sama sekali

kemudian yang ytmp3 error kayak gini

[ 12:41:09 ] (6283xxxxxxx => !ytmp3 https://youtu.be/uzOnR1u4ud4
video id =  uzOnR1u4ud4
`info.length_seconds` will be removed in a near future release, use `info.videoDetails.lengthSeconds` instead.
`info.length_seconds` will be removed in a near future release, use `info.videoDetails.lengthSeconds` instead.
107
os >>> Error: Command failed: ytdl mp3 https://youtu.be/uzOnR1u4ud4 -q highest -o mp4/uzOnR1u4ud4.mp4
C:\Users\Laptopku\AppData\Roaming\npm\node_modules\ytdl\node_modules\ytdl-core\lib\util.js:273
    throw Error(`No video id found: ${link}`);
    ^

Error: No video id found: mp3
    at Object.exports.getURLVideoID (C:\Users\Laptopku\AppData\Roaming\npm\node_modules\ytdl\node_modules\ytdl-core\lib\util.js:273:11)
    at Object.exports.getVideoID (C:\Users\Laptopku\AppData\Roaming\npm\node_modules\ytdl\node_modules\ytdl-core\lib\util.js:297:20)
    at Function.exports.<computed> [as getInfo] (C:\Users\Laptopku\AppData\Roaming\npm\node_modules\ytdl\node_modules\ytdl-core\lib\info.js:351:19)
    at ytdl (C:\Users\Laptopku\AppData\Roaming\npm\node_modules\ytdl\node_modules\ytdl-core\lib\index.js:17:8)
    at Object.<anonymous> (C:\Users\Laptopku\AppData\Roaming\npm\node_modules\ytdl\bin\ytdl.js:210:24)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ytdl mp3 https://youtu.be/uzOnR1u4ud4 -q highest -o mp4/uzOnR1u4ud4.mp4'
}

**Comment by fdciabdul** [comment]
belum ada ytmp3 🧛‍♂️

**Comment by xtrxrat** [comment]
> belum ada ytmp3 🧛‍♂️

bot nulisnya cuma ngirim gambar buku doang bang :'3

**Comment by fdciabdul** [comment]
iya kan emg masih ngebug
